update python runtime to 3.8 as 3.7 is eol
base2Services/aws-lambda-ecs-container-instance-check pull request #3
Opened 2023-10-26 02:22 UTC by tarunmenon95

2023-10-26 02:24 UTC, jaredbrook approved these changes

2023-10-26 07:34 UTC, aaronwalker requested changes

2023-10-26 07:34 UTC, aaronwalker commented on template.yaml
> +      Runtime: python3.8
@tarunmenon95 any reason why only 3.8 and not 3.10 or 3.11?

2023-10-27 15:30 UTC, aaronwalker approved these changes
LGTM

2023-10-27 15:32 UTC, merged